### ISSUE TITLE
Update Readme with Yarn Friendly Instructions

### ISSUE THREAD

**Issue by hmredmond** [statsbomb/eslint-config-statsbomb#1]
The instructions work fine for npm installs, but iqlive-ui uses yarn.  Would it be possible to add yarn instructions in as well?

I found that I am able to use yarn by adding the following to my `~/.npmrc` file (removed the folder from the registry url). 

```
//npm.pkg.github.com/:_authToken=AUTH_TOKEN
@statsbomb:registry=https://npm.pkg.github.com
```

**Comment by yodaddyp** [comment]
The directory name is probably not needed for npm either. I'll test it locally. 

Are there any other yarn specific installation instructions? ie is there a yarn equivalent for `npx`? I've not got yarn installed for testing.

**Comment by yodaddyp** [comment]
I've tested it locally, and the directory name is not required so I've updated the instructions (accidentally pushed to `master` 😅 🤐 - I need to lock the master branch still!).

If there are any other specific installation requirements for yarn (ie yarn/npx as queried above) can you open a PR?
