### ISSUE TITLE
Installation Stuff

### ISSUE THREAD

**Issue by graycodes** [statsbomb/eslint-config-statsbomb#2]
@yodaddyp 

Not sure why, but the installation didn't work for me as described in the README.

Took me a bit to work out but I had to do: 

```bash
npx install-peerdeps --dev -a <my_gh_auth_code> -r https://npm.pkg.github.com  @statsbomb/eslint-config

```

Not sure why it wouldn't pick up my credentials from npmrc. I tried installing through npm directly and it picked up the credentials fine so maybe a problem with the install-peerdeps lib itself.

In future, npm 7 I think will install peerdeps by default again so hopefully this issue will go away

**Comment by yodaddyp** [comment]
🤔 That is odd. What error message did you get when attempting to install? Is your `.npmrc` file installed in the project root or user config (ie `~/.npmrc`)? 

I did have an issue installing it in another project where a `.npmrc` file installed in the project root was overriding my user config.

**Comment by graycodes** [comment]
I didn't already have one anywhere, and I tried both in the end. The error
I got was basically a 404, saying it couldn't find the repo (because it
wasn't picking up the credentials)
