### ISSUE TITLE
403 Forbidden Error when not using SSO

### ISSUE THREAD

**Issue by wcardosodev** [statsbomb/eslint-config-statsbomb#4]
Just tried installing this on the IQ-Live project (using yarn) and was getting a "403 Forbidden" until enabling the SSO on the personal access token.

**Comment by yodaddyp** [comment]
Wow, sorry I missed this! Is this sorted now? You need to enable SSO on your PAT and then it should work.

**Comment by wcardosodev** [comment]
Luckily it's all good now @yodaddyp, I'd probably be fired by now if not! 😆 

I think the point of this issue (though I wasn't clear at all I apologise) was that enabling the SSO should be added into the readme as I can't see it in there so others might have that issue in future. (If it is in there already I clearly need glasses...)
